In [1]:
AngkorWat = (13.4125, 103.866667)
print (AngkorWat[0])

13.4125

In [7]:
AngkorWat

(13.4125, 103.866667)

In [20]:
if type(AngkorWat) is str:
    print ("Hello")

In [33]:
print("Angkor Wat is at latitude:{}".format(AngkorWat[0]))

Angkor Wat is at latitude:13.4125

In [34]:
dimension = 1,2,3
type(dimension)

tuple

In [36]:
height, width, depth = dimension
type(height)
#type(width)
#type(depth)

int

In [53]:
class Solution:
    def sortArrayByParity(self, A):
        """
        :type A: List[int]
        :rtype: List[int]
        """
        if len(A) ==0 or len(A) > 5000:
            print("Array exceeds max size")
            return None
        
        ArrayB = []
        for val in A:
            if val <0 or val > 5000:
                print("Bad value in array. Abort the function")
                return None
            
            if val % 2 == 0:
                ArrayB.insert(0, val)
            else:
                ArrayB.append(val)
        return ArrayB

sol = Solution()
array=[1,4,500000,3,2]
print (sol.sortArrayByParity(array))

Bad value in array. Abort the function
None

In [77]:
class Solution:
    def merge(self, nums1, m, nums2, n):
        """
        :type nums1: List[int]
        :type m: int
        :type nums2: List[int]
        :type n: int
        :rtype: void Do not return anything, modify nums1 in-place instead.
        """
        idx1 = 0
        idx2 = 0
        temparray = []
        
        # go through the m elements in nums1 and n elements in nums2 to merge
        while True:
            if nums1[idx1] <= nums2[idx2]:
                temparray.append(nums1[idx1])
                idx1 += 1
            else:
                temparray.append(nums2[idx2])
                idx2 += 1

            #if exceed m elements in nums1 or n elements in nums2, exit the loop
            if idx1 >= m or idx2 >= n:
                break
            else:
                continue

        if idx1 < m:
            for ii in range(idx1,m):
                temparray.append(nums1[ii])
        else:
            for ii in range(idx2, n):
                temparray.append(nums2[ii])
        nums1.clear()
        for elem in temparray:
            nums1.append(elem)

sol = Solution()
nums1=[1,2,3,0,0,0]
nums2=[2,5,6]
sol.merge(nums1, 3, nums2, 3)
print(nums1)

[1, 2, 2, 3, 5, 6]

In [78]:
class Solution:
    def flipAndInvertImage(self, A):
        """
        :type A: List[List[int]]
        :rtype: List[List[int]]
        """
        print(A)
        for llist in A:
            llist.reverse()
            for ii in range(0,len(llist)):
                llist[ii] = llist[ii] ^ 1
        print(A)


sol = Solution()
array=[[1,1,0],[1,0,1],[0,0,0]]
sol.flipAndInvertImage(array)
print(array)

[[1, 1, 0], [1, 0, 1], [0, 0, 0]]
[[1, 0, 0], [0, 1, 0], [1, 1, 1]]
[[1, 0, 0], [0, 1, 0], [1, 1, 1]]

In [89]:
def hours2days(hours):
    days = hours//24
    rhours = hours % 24
    return (days, rhours)
    
if __name__ == "__main__":
    print(hours2days(45))

(1, 21)

In [87]:
def nearest_square(limit):
    """ Find the largest square number smaller than limit. """
    answer = 0
    answer = int(limit ** .5)
    return answer**2

nearest_square(20)

16

In [90]:
egg_count = 0

def buy_eggs():
    egg_count += 12 # purchase a dozen eggs

buy_eggs()

UnboundLocalError: local variable 'egg_count' referenced before assignment

In [91]:
with open("/Users/stevsun/jupyter_space/Data analysis/table_descriptions.txt") as fd:
    file_content = fd.read()
    words = file_content.split()
    for dd in words:
        print("dd = ", dd)

dd =  enrollments.csv:
dd =  Data
dd =  about
dd =  a
dd =  random
dd =  subset
dd =  of
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  students
dd =  who
dd =  complete
dd =  their
dd =  first
dd =  project
dd =  and
dd =  a
dd =  random
dd =  subset
dd =  of
dd =  students
dd =  who
dd =  do
dd =  not.
dd =  Columns:
dd =  -
dd =  account_key:
dd =  A
dd =  unique
dd =  identifier
dd =  for
dd =  the
dd =  account
dd =  of
dd =  the
dd =  student
dd =  who
dd =  enrolled.
dd =  -
dd =  status:
dd =  The
dd =  enrollment
dd =  status
dd =  of
dd =  the
dd =  student
dd =  at
dd =  the
dd =  time
dd =  the
dd =  data
dd =  was
dd =  collected.
dd =  Possible
dd =  values
dd =  are
dd =  'canceled'
dd =  and
dd =  'current'.
dd =  -
dd =  join_date:
dd =  The
dd =  date
dd =  the
dd =  student
dd =  enrolled.
dd =  -
dd =  cancel_date:
dd =  The
dd =  date
dd =  the
dd =  student
dd =  canceled,
dd =  or
dd =  blank
dd =  if
dd =  the
dd =  student
dd =  has
dd =  not
dd =  yet
dd =  canceled.
dd =  -
dd =  days_to_cancel:
dd =  The
dd =  number
dd =  of
dd =  days
dd =  between
dd =  join_date
dd =  and
dd =  cancel_date,
dd =  or
dd =  blank
dd =  if
dd =  the
dd =  student
dd =  has
dd =  not
dd =  yet
dd =  canceled.
dd =  -
dd =  is_udacity:
dd =  True
dd =  if
dd =  the
dd =  account
dd =  is
dd =  a
dd =  Udacity
dd =  test
dd =  account,
dd =  False
dd =  otherwise.
dd =  -
dd =  is_canceled:
dd =  True
dd =  if
dd =  the
dd =  student
dd =  had
dd =  canceled
dd =  this
dd =  enrollment
dd =  at
dd =  the
dd =  time
dd =  the
dd =  data
dd =  was
dd =  collected,
dd =  False
dd =  otherwise.
dd =  -------------------------------------------------------------------------------
dd =  daily_engagement.csv:
dd =  Data
dd =  about
dd =  engagement
dd =  within
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  courses
dd =  for
dd =  each
dd =  student
dd =  in
dd =  the
dd =  enrollment
dd =  table
dd =  on
dd =  each
dd =  day
dd =  they
dd =  were
dd =  enrolled.
dd =  Includes
dd =  a
dd =  record
dd =  even
dd =  if
dd =  there
dd =  was
dd =  no
dd =  engagement
dd =  that
dd =  day.
dd =  Includes
dd =  engagement
dd =  data
dd =  from
dd =  both
dd =  the
dd =  supporting
dd =  courses
dd =  for
dd =  the
dd =  Nanodegree
dd =  program,
dd =  and
dd =  the
dd =  corresponding
dd =  freely
dd =  available
dd =  courses
dd =  with
dd =  the
dd =  same
dd =  content.
dd =  Columns:
dd =  -
dd =  acct:
dd =  A
dd =  unique
dd =  identifier
dd =  for
dd =  the
dd =  account
dd =  of
dd =  the
dd =  student
dd =  whose
dd =  engagement
dd =  data
dd =  this
dd =  is.
dd =  -
dd =  utc_date:
dd =  The
dd =  date
dd =  for
dd =  which
dd =  the
dd =  data
dd =  was
dd =  collected.
dd =  -
dd =  num_courses_visited:
dd =  The
dd =  total
dd =  number
dd =  of
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  courses
dd =  the
dd =  student
dd =  visited
dd =  for
dd =  at
dd =  2
dd =  minutes
dd =  on
dd =  this
dd =  day.
dd =  Nanodegree
dd =  courses
dd =  and
dd =  freely
dd =  available
dd =  courses
dd =  with
dd =  the
dd =  same
dd =  content
dd =  are
dd =  counted
dd =  separately.
dd =  -
dd =  total_minutes_visited:
dd =  The
dd =  total
dd =  number
dd =  of
dd =  minutes
dd =  the
dd =  student
dd =  spent
dd =  taking
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  courses
dd =  on
dd =  this
dd =  day.
dd =  -
dd =  lessons_completed:
dd =  The
dd =  total
dd =  number
dd =  of
dd =  lessons
dd =  within
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  courses
dd =  on
dd =  this
dd =  day.
dd =  -
dd =  projects_completed:
dd =  The
dd =  total
dd =  number
dd =  of
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  projects
dd =  the
dd =  student
dd =  completed
dd =  on
dd =  this
dd =  day.
dd =  -------------------------------------------------------------------------------
dd =  project_submissions.csv:
dd =  Data
dd =  about
dd =  submissions
dd =  for
dd =  Data
dd =  Analyst
dd =  Nanodegree
dd =  projects
dd =  for
dd =  each
dd =  student
dd =  in
dd =  the
dd =  enrollment
dd =  table.
dd =  Columns:
dd =  -
dd =  creation_date:
dd =  The
dd =  date
dd =  the
dd =  project
dd =  was
dd =  submitted.
dd =  -
dd =  completion_date:
dd =  The
dd =  date
dd =  the
dd =  project
dd =  was
dd =  evaluated.
dd =  -
dd =  assigned_rating:
dd =  This
dd =  column
dd =  has
dd =  4
dd =  possible
dd =  values:
dd =  blank
dd =  -
dd =  Project
dd =  has
dd =  not
dd =  yet
dd =  been
dd =  evaluated.
dd =  INCOMPLETE
dd =  -
dd =  Project
dd =  did
dd =  not
dd =  meet
dd =  specifications.
dd =  PASSED
dd =  -
dd =  Project
dd =  met
dd =  specifications.
dd =  DISTINCTION
dd =  -
dd =  Project
dd =  exceeded
dd =  specifications.
dd =  UNGRADED
dd =  -
dd =  The
dd =  submission
dd =  could
dd =  not
dd =  be
dd =  evaluated
dd =  (e.g.
dd =  contained
dd =  a
dd =  corrupted
dd =  file)
dd =  -
dd =  account_key:
dd =  A
dd =  unique
dd =  identifier
dd =  for
dd =  the
dd =  account
dd =  of
dd =  the
dd =  student
dd =  who
dd =  submitted
dd =  the
dd =  project.
dd =  -
dd =  lesson_key:
dd =  A
dd =  unique
dd =  identifier
dd =  for
dd =  the
dd =  project
dd =  that
dd =  was
dd =  submitted.
dd =  -
dd =  processing_state:
dd =  This
dd =  column
dd =  has
dd =  2
dd =  possible
dd =  values:
dd =  CREATED
dd =  -
dd =  Project
dd =  has
dd =  been
dd =  submitted
dd =  but
dd =  not
dd =  evaluated.
dd =  EVALUATED
dd =  -
dd =  Project
dd =  has
dd =  been
dd =  evaluated.
dd =  -------------------------------------------------------------------------------
dd =  daily_engagement_full.csv:
dd =  Similar
dd =  to
dd =  daily_engagement.csv,
dd =  but
dd =  with
dd =  engagement
dd =  further
dd =  broken
dd =  down
dd =  by
dd =  course
dd =  and
dd =  with
dd =  more
dd =  columns
dd =  available.
dd =  This
dd =  file
dd =  is
dd =  about
dd =  500
dd =  megabytes,
dd =  which
dd =  is
dd =  why
dd =  the
dd =  smaller
dd =  daily_engagement.csv
dd =  file
dd =  was
dd =  created.
dd =  This
dd =  dataset
dd =  is
dd =  optional;
dd =  it
dd =  is
dd =  not
dd =  needed
dd =  to
dd =  complete
dd =  the
dd =  course.
dd =  In
dd =  addition
dd =  to
dd =  the
dd =  following
dd =  columns,
dd =  this
dd =  table
dd =  also
dd =  contains
dd =  all
dd =  the
dd =  same
dd =  columns
dd =  as
dd =  daily_engagement.csv,
dd =  except
dd =  with
dd =  has_visited
dd =  instead
dd =  of
dd =  num_courses_visited.
dd =  Columns:
dd =  -
dd =  registration_date:
dd =  Date
dd =  the
dd =  account
dd =  was
dd =  registered.
dd =  -
dd =  subscription_start:
dd =  Date
dd =  paid
dd =  subscription
dd =  for
dd =  the
dd =  account
dd =  started.
dd =  -
dd =  course_key:
dd =  Course
dd =  in
dd =  which
dd =  activity
dd =  is
dd =  recorded.
dd =  -
dd =  sibling_key:
dd =  Free
dd =  course
dd =  with
dd =  the
dd =  same
dd =  free
dd =  content
dd =  as
dd =  course_key.
dd =  If
dd =  course_key
dd =  is
dd =  a
dd =  free
dd =  course,
dd =  course_key
dd =  and
dd =  sibling_key
dd =  are
dd =  the
dd =  same.
dd =  -
dd =  course_title:
dd =  Title
dd =  of
dd =  the
dd =  course.
dd =  -
dd =  has_visited:
dd =  1
dd =  if
dd =  the
dd =  student
dd =  visited
dd =  this
dd =  course
dd =  for
dd =  at
dd =  least
dd =  2
dd =  minutes
dd =  on
dd =  this
dd =  day.

In [93]:
with open("/Users/stevsun/jupyter_space/Data analysis/table_descriptions.txt") as fd:
    document=fd.read(100)
    words = document.split()
    print (words)

['enrollments.csv:', 'Data', 'about', 'a', 'random', 'subset', 'of', 'Data', 'Analyst', 'Nanodegree', 'students', 'who', 'complete', 'their']

In [97]:
cast_list = []

with open("/Users/stevsun/jupyter_space/Data analysis/flying_circus_cast.txt") as fd:
    for line in fd:
        token_list=line.split()
        cast_list.append([token_list[0], token_list[1]])
        
print(cast_list)

[['Graham', 'Chapman,'], ['Eric', 'Idle,'], ['Terry', 'Jones,'], ['Michael', 'Palin,'], ['Terry', 'Gilliam,'], ['John', 'Cleese,'], ['Carol', 'Cleveland,'], ['Ian', 'Davidson,'], ['John', 'Hughman,'], ['The', 'Fred'], ['Connie', 'Booth,'], ['Bob', 'Raymond,'], ['Lyn', 'Ashley,'], ['Rita', 'Davies,'], ['Stanley', 'Mason,'], ['David', 'Ballantyne,'], ['Donna', 'Reading,'], ['Peter', 'Brett,'], ['Maureen', 'Flanagan,'], ['Katya', 'Wyeth,'], ['Frank', 'Lester,'], ['Neil', 'Innes,'], ['Dick', 'Vosburgh,'], ['Sandra', 'Richards,'], ['Julia', 'Breck,'], ['Nicki', 'Howorth,'], ['Jimmy', 'Hill,'], ['Barry', 'Cryer,'], ['Jeannette', 'Wild,'], ['Marjorie', 'Wilde,'], ['Marie', 'Anderson,'], ['Caron', 'Gardner,'], ['Nosher', 'Powell,'], ['Carolae', 'Donoghue,'], ['Vincent', 'Wong,'], ['Helena', 'Clayton,'], ['Nigel', 'Jones,'], ['Roy', 'Gunson,'], ['Daphne', 'Davey,'], ['Stenson', 'Falke,'], ['Alexander', 'Curry,'], ['Frank', 'Williams,'], ['Ralph', 'Wood,'], ['Rosalind', 'Bailey,'], ['Marion', 'Mould,'], ['Sheila', 'Sands,'], ['Richard', 'Baker,'], ['Douglas', 'Adams,'], ['Ewa', 'Aulin,'], ['Reginald', 'Bosanquet,'], ['Barbara', 'Lindley,'], ['Roy', 'Brent,'], ['Jonas', 'Card,'], ['Tony', 'Christopher,'], ['Beulah', 'Hughes,'], ['Peter', 'Kodak,'], ['Lulu,', 'Herself'], ['Jay', 'Neill,'], ['Graham', 'Skidmore,'], ['Ringo', 'Starr,'], ['Fred', 'Tomlinson,'], ['David', 'Hamilton,'], ['Suzy', 'Mandel,'], ['Peter', 'Woods,']]

In [101]:
from datetime import datetime
import pytz

utc = pytz.utc
itc = pytz.timezone("Asia/Kolkata")

udate = datetime.now(utc)
idate = datetime.now(itc)

print (udate)
print (idate)

2018-09-22 00:27:35.917717+00:00
2018-09-22 05:57:35.917771+05:30

In [104]:
def todo_list(new_task, base_list=['wake up']):
    base_list.append(new_task)
    return base_list

#print(todo_list("check the mail"))
print(todo_list("begin orbital transfer"))

['wake up', 'begin orbital transfer']

In [162]:
class Solution:
    def canPlaceFlowers(self, flowerbed, n):
        """
        :type flowerbed: List[int]
        :type n: int
        :rtype: bool
        """
        size = len(flowerbed)
        idx = 0
        totalspots = 0
        while True:
            # start counting plantable spots until hitting the end of array
            if flowerbed[idx] == 0:
                if (size == 1) or (idx == 0 and flowerbed[idx+1] == 0) or (idx == size-1 and flowerbed[idx-1]==0) or (flowerbed[idx-1] == 0 and flowerbed[idx+1] == 0):
                    totalspots += 1            
            if idx >= size - 1:
                break
            
            idx +=1
            continue

        if n <= totalspots:
            return True
        else:
            return False
        
flowerbed=[0,0,1]
sol = Solution()
print(sol.canPlaceFlowers(flowerbed, 1))

True

In [ ]:
lib1 = {}